apiVersion: tekton.dev/v1alpha1
kind: PipelineResource
metadata:
  name: quarkuscoffeeshop-customermocker-git
  labels:
    app: quarkuscoffeeshop-customermocker
  namespace: quarkuscoffeeshop-cicd
spec:
  type: git
  params:
  - name: url
    value: https://{{ .Values.global.git.hostname }}/{{ .Values.global.git.account }}}/quarkuscoffeeshop-customermocker
  - name: revision
    value: {{ .Values.global.quarkuscoffeeshopCustomermocker.revision | quote }}