apiVersion: tekton.dev/v1alpha1
kind: Pipeline
metadata:
  name: build-and-push-to-edge
  labels:
    app: quarkuscoffeeshop-majestic-monolith
  namespace: quarkuscoffeeshop-cicd
spec:
  params:
    - default: latest
      description: Image Tag Value
      name: IMAGE_TAG
      type: string
    - default: main
      description: Select Branch 
      name: branch_name
      type: string
    - default: quay.io/quarkuscoffeeshop/quarkuscoffeeshop-majestic-monolith
      name: quay-io-repository
      type: string
    - default: latest
      name: quay-io-image-tag-name
      type: string
    - default: webhook-secret
      description: Webhook secret name
      name: webhook-secret
      type: string
    - default: >-
        --patch={"spec":{"template":{"spec":{"containers":[{"name":"quarkuscoffeeshop-majestic-monolith","image":"image-registry.openshift-image-registry.svc:5000/quarkuscoffeeshop-cicd/quarkuscoffeeshop-majestic-monolith:$(params.IMAGE_TAG)"}]}}}}
      description: patch image
      name: PATCH_IMAGE
      type: string
    - default: 192.168.1.10
      description: Ansible Tower Instance
      name: tower_host
      type: string
    - default: 10.0.1.20
      description:  Target Edge Device
      name: target_edge_device
      type: string
    - default: "25"
      description:  Ansible Tower Job Template Default is `Update quarkuscoffeeshop-majestic-monolith Application` the number is found in the URL
      name: tower_job_template
      type: string
    - default: "1"
      description:  Ansible Tower Inventory number is  found in url 
      name: tower_inventory
      type: string
    - default: "1"
      description:  Ansible Tower Credential number is  found in url 
      name: tower_credential
      type: string
  resources:
    - name: app-git
      type: git
    - name: image
      type: image
  tasks:
    - name: fetch-repository
      params:
        - name: url
          value: 'https://github.com/jeremyrdavis/quarkuscoffeeshop-majestic-monolith'
        - name: subdirectory
          value: ''
        - name: deleteExisting
          value: 'true'
        - name: revision
          value: $(params.branch_name)
      taskRef:
        kind: Task
        name: git-clone
      workspaces:
        - name: output
          workspace: shared-workspace
    - name: maven-run
      params:
        - name: CONTEXT_DIR
          value: .
        - name: GOALS
          value:
            - '-DskipTests'
            - clean
            - package
      runAfter:
        - fetch-repository
      taskRef:
        kind: Task
        name: maven
      workspaces:
        - name: maven-settings
          workspace: maven-settings
        - name: source
          workspace: shared-workspace
    - name: build-java-app-image
      params:
        - name: CONTEXT
          value: .
        - name: DOCKERFILE
          value: src/main/docker/Dockerfile.jvm
        - name: IMAGE
          value: >-
            image-registry.openshift-image-registry.svc:5000/quarkuscoffeeshop-cicd/quarkuscoffeeshop-majestic-monolith:$(params.IMAGE_TAG)
        - name: TLSVERIFY
          value: 'false'
      runAfter:
        - maven-run
      taskRef:
        kind: ClusterTask
        name: buildah
      workspaces:
        - name: source
          workspace: shared-workspace
    - name: tag-test-image
      params:
        - name: ARGS
          value:
            - tag
            - 'quarkuscoffeeshop-majestic-monolith:$(params.IMAGE_TAG)'
            - 'quarkuscoffeeshop-majestic-monolith:latest'
      runAfter:
        - build-java-app-image
      taskRef:
        kind: ClusterTask
        name: openshift-client
    - name: push-to-test-env
      params:
        - name: ARGS
          value:
            - patch
            - deployment/quarkuscoffeeshop-majestic-monolith
            - $(params.PATCH_IMAGE)
            - '-n'
            - quarkuscoffeeshop-demo
      runAfter:
        - tag-test-image
      taskRef:
        kind: ClusterTask
        name: openshift-client
    - name: push-quarkuscoffeeshop-majestic-monolith-image-to-quay
      params:
        - name: quay-io-repository
          value: $(params.quay-io-repository)
        - name: quay-io-image-tag-name
          value: $(params.quay-io-image-tag-name)
      resources:
        inputs:
          - name: image
            resource: image
      runAfter:
        - push-to-test-env
      taskRef:
        kind: Task
        name: push-quarkuscoffeeshop-majestic-monolith-image-to-quay
    - name: push-quarkuscoffeeshop-majestic-monolith-image-to-quay-latest
      params:
        - name: quay-io-repository
          value: $(params.quay-io-repository)
        - name: quay-io-image-tag-name
          value: latest
      resources:
        inputs:
          - name: image
            resource: image
      runAfter:
        - push-quarkuscoffeeshop-majestic-monolith-image-to-quay
      taskRef:
        kind: Task
        name: push-quarkuscoffeeshop-majestic-monolith-image-to-quay-latest
    - name: send-to-webhook-slack
      params:
        - name: webhook-secret
          value: $(params.webhook-secret)
        - name: message
          value: >-
            Pipeline build pushed succesfully to 
            $(params.quay-io-repository):$(params.quay-io-image-tag-name)
      runAfter:
        - push-quarkuscoffeeshop-majestic-monolith-image-to-quay-latest
      taskRef:
        kind: Task
        name: send-to-webhook-slack
    - name: deploy-application-to-edge
      taskRef:
        name: ansible-tower-cli
      params:
      - name: SSLVERIFY
        value: "false"
      - name: HOST
        value: $(params.tower_host)
      - name: tower-secret
        value: "tower-creds"
      - name: ARGS
        value:
          - job
          - launch
          - "--job-template"
          - "$(params.tower_job_template)"
          - "--extra-vars"
          - 'external_endpoint=$(params.target_edge_device)'
          - "--inventory"
          - "$(params.tower_inventory)"
          - --credential
          - "$(params.tower_credential)"
          - "--monitor"
      runAfter:
        - send-to-webhook-slack
  workspaces:
    - name: shared-workspace
    - name: maven-settings
