clusterGroup:
  name: hub
  isHubCluster: true
  # Note: setting this to true stores the vault unseal keys inside a cluster secret and
  # is fundamentally insecure
  insecureUnsealVaultInsideCluster: true

  namespaces:
    - open-cluster-management
    - vault
    - golang-external-secrets
    - landing-page
    - coffeeshop-homeoffice
    - coffeeshop-store
    - quarkuscoffeeshop-cicd
    - quarkuscoffeeshop-demo
    - quarkuscoffeeshop-integration

  subscriptions:
    acm:
      name: advanced-cluster-management
      namespace: open-cluster-management
      channel: release-2.5

    pipelines:
      name: openshift-pipelines-operator-rh

    amqstreams-homeoffice:
      name: amq-streams
      namespace: openshift-operators
      channel: amq-streams-2.x

    crunchypgo-homeoffice:
      name: crunchy-postgres-operator
      namespace: openshift-operators
      channel: v5
      source: certified-operators

  projects:
    - hub
    - coffeeshop-homeoffice
    - coffeeshop-store
    - coffeeshop-demo

  applications:
    acm:
      name: acm
      namespace: open-cluster-management
      project: hub
      path: common/acm
      ignoreDifferences:
      - group: internal.open-cluster-management.io
        kind: ManagedClusterInfo
        jsonPointers:
          - /spec/loggingCA

    quarkuscoffeeshop-cicd:
      name: quarkuscoffeeshop-cicd
      namespace: quarkuscoffeeshop-cicd
      project: hub
      path: charts/hub/quarkuscoffeeshop-pipelines

    vault:
      name: vault
      namespace: vault
      project: hub
      path: common/hashicorp-vault

    golang-external-secrets:
      name: golang-external-secrets
      namespace: golang-external-secrets
      project: hub
      path: common/golang-external-secrets

    landing-page:
      name: landing-page
      namespace: landing-page
      project: hub
      path: charts/hub/landing-page

    coffeeshopdb-store:
      name: coffeeshopdb-store
      namespace: coffeeshop-store
      project: coffeeshop-store
      path: charts/all/crunchy-pgcluster
      extraValueFiles:
        - /values-db-store.yaml

    coffeeshopdb-homeoffice:
      name: coffeeshopdb-homeoffice
      namespace: coffeeshop-homeoffice
      project: coffeeshop-homeoffice
      path: charts/all/crunchy-pgcluster
      extraValueFiles:
        - /values-db-homeoffice.yaml

    coffeeshop-test:
      name: coffeeshop-demo
      namespace: coffeeshop-demo
      project: coffeeshop-demo
      path: charts/store/quarkuscoffeeshop-charts
      overrides:
        - name: projectnamespace
          value: coffeeshop-demo
        - name: Release.release-namespace
          value: coffeeshop-demo
        - name: storeid
          value: TEST

    coffeeshopdb-test:
      name: coffeeshopdb-demo
      namespace: coffeeshop-demo
      project: coffeeshop-demo
      path: charts/all/crunchy-pgcluster
      extraValueFiles:
        - /values-db-store.yaml

    coffeeshop-test-kafka:
      name: coffeeshop-test-kafka
      namespace: coffeeshop-demo
      project: coffeeshop-demo
      path: charts/all/quarkuscoffeeshop-kafka

    coffeeshop-store:
      name: coffeeshop-store
      namespace: coffeeshop-store
      project: coffeeshop-store
      path: charts/store/quarkuscoffeeshop-charts
      overrides:
        - name: projectnamespace
          value: coffeeshop-store
        - name: Release.release-namespace
          value: coffeeshop-store

    coffeeshop-store-kafka:
      name: coffeeshop-store-kafka
      namespace: coffeeshop-store
      project: coffeeshop-store
      path: charts/all/quarkuscoffeeshop-kafka

    coffeeshop-homeoffice-kafka:
      name: coffeeshop-homeoffice-kafka
      namespace: coffeeshop-homeoffice
      project: coffeeshop-homeoffice
      path: charts/all/quarkuscoffeeshop-kafka

  imperative:
    # NOTE: We *must* use lists and not hashes. As hashes lose ordering once parsed by helm
    # The default schedule is every 10 minutes: imperative.schedule
    # Total timeout of all jobs is 1h: imperative.activeDeadlineSeconds
    # imagePullPolicy is set to always: imperative.imagePullPolicy
    # For additional overrides that apply to the jobs, please refer to
    # https://hybrid-cloud-patterns.io/imperative-actions/#additional-job-customizations
    jobs: []
    #- name: noop
      # ansible playbook to be run
    #  playbook: ansible/playbooks/noop.yml
      # per playbook timeout in seconds
   #   timeout: 234
      # verbosity: "-v"

#  managedClusterGroups:
#    region-one:
#      name: region-one
#      helmOverrides:
#      - name: clusterGroup.isHubCluster
#        value: false
#      clusterSelector:
#        matchLabels:
#          clusterGroup: region-one

#  To have apps in multiple flavors, use namespaces and use helm overrides as appropriate
#
#    pipelines:
#      name: pipelines
#      namespace: production
#      project: datacenter
#      path: applications/pipeline
#      repoURL: https://github.com/you/applications.git
#      targetRevision: stable
#      overrides:
#      - name: myparam
#        value: myparam
#
#    pipelines_staging:
#    - name: pipelines
#      namespace: staging
#      project: datacenter
#      path: applications/pipeline
#      repoURL: https://github.com/you/applications.git
#      targetRevision: main
#
#   Additional applications
#   Be sure to include additional resources your apps will require
#   +X machines
#   +Y RAM
#   +Z CPU
#    vendor-app:
#      name: vendor-app
#      namespace: default
#      project: vendor
#      path: path/to/myapp
#      repoURL: https://github.com/vendor/applications.git
#      targetRevision: main

#  managedSites:
#    factory:
#      name: factory
#      # repoURL: https://github.com/dagger-refuse-cool/manuela-factory.git
#      targetRevision: main
#      path: applications/factory
#      helmOverrides:
#      - name: site.isHubCluster
#        value: false
#      clusterSelector:
#        matchExpressions:
#        - key: vendor
#          operator: In
#          values:
#            - OpenShift
