apiVersion: tekton.dev/v1alpha1
kind: PipelineResource
metadata:
  name: quarkuscoffeeshop-inventory-git
  labels:
    app: quarkuscoffeeshop-inventory
spec:
  type: git
  params:
  - name: url
    value: https://{{ .Values.global.git.hostname }}/{{ .Values.global.git.account }}/quarkuscoffeeshop-inventory
  - name: revision
    value: {{ .Values.global.quarkuscoffeeshopInventory.revision | quote }}
