apiVersion: tekton.dev/v1alpha1
kind: PipelineResource
metadata:
  name: homeoffice-ingress-git
  labels:
    app: homeoffice-ingress
  namespace: quarkuscoffeeshop-cicd
spec:
  type: git
  params:
  - name: url
    value: https://{{ .Values.global.git.hostname }}/{{ .Values.global.git.account }}/homeoffice-ingress
  - name: revision
    value: {{ .Values.global.homeofficeIngress.revision | quote }}
