---
apiVersion: v1
kind: ServiceAccount
metadata:
  # pipeline is configured in the openshift-pipelines namespace as the default serviceaccount for pipelineruns
  # So let's use that as our primary serviceaccount
  # To change this setting, edit the configmap config-defaults in ns openshift-pipelines
  name: pipeline
secrets:
  - name: quay-auth-secret
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: pipeline-edit
  namespace: openshift
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: edit
subjects:
  - kind: ServiceAccount
    name: pipeline
    namespace: {{ .Values.buildNamespace }}
  #- kind: ServiceAccount
  #  name: pipeline
  #  namespace: quarkuscoffeeshop-demo
---
kind: RoleBinding
  apiVersion: rbac.authorization.k8s.io/v1
  metadata:
    name: admin
    namespace: {{ .Values.testNamespace }}
  subjects:
    - kind: ServiceAccount
      name: pipeline
      namespace: {{ .Values.buildNamespace }}
  roleRef:
    apiGroup: rbac.authorization.k8s.io
    kind: ClusterRole
    name: admin
