apiVersion: tekton.dev/v1alpha1
kind: PipelineResource
metadata:
  name: quarkuscoffeeshop-counter-git
  labels:
    app: quarkuscoffeeshop-counter
spec:
  type: git
  params:
  - name: url
    value: https://{{ .Values.global.git.hostname }}/{{ .Values.global.git.account }}/quarkuscoffeeshop-counter
  - name: revision
    value: {{ .Values.global.quarkuscoffeeshopCounter.revision | quote }}
