apiVersion: tekton.dev/v1alpha1
kind: PipelineResource
metadata:
  name: quarkuscoffeeshop-homeoffice-ui-image
  labels:
    app: quarkuscoffeeshop-homeoffice-ui
spec:
  type: image
  params:
  - name: url
    value: image-registry.openshift-image-registry.svc:5000/quarkuscoffeeshop-cicd/quarkuscoffeeshop-homeoffice-ui
