apiVersion: tekton.dev/v1alpha1
kind: PipelineResource
metadata:
  name: quarkuscoffeeshop-web-git
  labels:
    app: quarkuscoffeeshop-web
spec:
  type: git
  params:
  - name: url
    value: https://{{ .Values.global.git.hostname }}/{{ .Values.global.git.account }}/quarkuscoffeeshop-web
  - name: revision
    value: {{ .Values.global.quarkuscoffeeshopWeb.revision | quote }}
