apiVersion: tekton.dev/v1alpha1
kind: PipelineResource
metadata:
  name: quarkuscoffeeshop-kitchen-git
  labels:
    app: quarkuscoffeeshop-kitchen
spec:
  type: git
  params:
  - name: url
    value: https://{{ .Values.global.git.hostname }}/{{ .Values.global.git.account }}/quarkuscoffeeshop-kitchen
  - name: revision
    value: {{ .Values.global.quarkuscoffeeshopKitchen.revision | quote }}
