{{ if .Values.enableWebhookSecret }}
---
apiVersion: triggers.tekton.dev/v1alpha1
kind: TriggerTemplate
metadata:
  name: quarkuscoffeeshop-homeoffice-ui-build-triggertemplate
spec:
  params:
    - name: gitrevision
      description: The git revision
      default: main
    - name: gitrepositoryurl
      description: The git repository url
  resourcetemplates:
    - apiVersion: tekton.dev/v1alpha1
      kind: PipelineResource
      metadata:
        name: quarkuscoffeeshop-homeoffice-ui-git-$(uid)
      spec:
        type: git
        params:
        - name: revision
          value: $(params.gitrevision)
        - name: url
          value: $(params.gitrepositoryurl)
        - name: sslVerify
          value: "false"
    - apiVersion: tekton.dev/v1alpha1
      kind: PipelineRun
      metadata:
        name: build-and-push-quarkuscoffeeshop-homeoffice-ui-$(uid)
      spec:
        pipelineRef:
          name: build-and-push-quarkuscoffeeshop-homeoffice-ui
        serviceAccountName: pipeline
        params:
          - name: quay-io-account
            value: 'takinosh'
          - name: quay-io-repository
            value: "quay.io/quarkuscoffeeshop/quarkuscoffeeshop-homeoffice-ui"
          - name: quay-io-image-tag-name
            value: $(params.gitrevision)
          - name: STORAGE_DRIVER
            value: "Overlay"
          - name: IMAGE_TAG
            value: $(params.gitrevision)
        resources:
          - name: app-git
            resourceRef:
              name: reversewords-git-$(uid)
          - name: image
            type: image
---
apiVersion: triggers.tekton.dev/v1alpha1
kind: EventListener
metadata:
  name: homeoffice-ui-webhook
spec:
  serviceAccountName: quarkuscoffeeshop-pipelines
  triggers:
    - name: git-quarkuscoffeeshop-homeoffice-ui-trigger
      interceptors:
        - github:
            secretRef:
              secretName: webhook-secret
              secretKey: secret
            eventTypes:
              - push
      bindings:
        - name: pipeline-binding
          ref: github-triggerbinding
      template:
        name: quarkuscoffeeshop-homeoffice-ui-build-triggertemplate
{{ end }}