apiVersion: v1
kind: ConfigMap
metadata:
  name: landing-page-configmap
  labels:
    app.kubernetes.io/instance: landing-page
data:
  "index.html": |-
    <!DOCTYPE html>
      <html lang="en">
        <head>
          <meta charset="utf-8">
            <title>Quarkus Coffeeshop Landing Page</title>
        </head>
          <body>
            <h1>
            <a href="http://quarkuscoffeeshop-web-coffeeshop-store.{{ .Values.global.localClusterDomain }}">Store Web Page</a>
            <hr/>
            <a href="http://kafdrop-coffeeshop-store.{{ .Values.global.localClusterDomain }}">Kafdrop Kafka WebUI for Store</a>
            </h1>
          </body>
      </html>
