apiVersion: image.openshift.io/v1
kind: ImageStream
metadata:
  name: landing-page
spec:
  lookupPolicy:
    local: true
  tags:
  - name: registry.access.redhat.com/ubi8/httpd-24
    importPolicy: {}
    referencePolicy:
      type: Local
